# Mathematical functions

In [1]:
import numpy as np

## Trigonometric functions

Q1. Calculate sine, cosine, and tangent of x, element-wise.

In [26]:
x = np.array([0., 1., 30, 90])


sine: [ 0.          0.84147098 -0.98803162  0.89399666]
cosine: [ 1.          0.54030231  0.15425145 -0.44807362]
tangent: [ 0.          1.55740772 -6.4053312  -1.99520041]


In [7]:
x = np.array([0., 1., 30, 90])
sine = np.sin(x)
print('sine: ', sine)
cosine = np.cos(x)
print ('cosine: ', cosine)
tangent = np.tan(x)
print ('tangent: ', tangent)

sine:  [ 0.          0.84147098 -0.98803162  0.89399666]
cosine:  [ 1.          0.54030231  0.15425145 -0.44807362]
tangent:  [ 0.          1.55740772 -6.4053312  -1.99520041]


Q2. Calculate inverse sine, inverse cosine, and inverse tangent of x, element-wise.

In [31]:
x = np.array([-1., 0, 1.])


inverse sine: [ 1.57079633  0.          1.57079633]
inverse cosine: [ 0.          1.57079633  0.        ]
inverse tangent: [ 0.78539816  0.          0.78539816]


In [8]:
x = np.array([-1., 0, 1.])
a = np.arcsin(x)
b = np.arccos(x)
c = np.arctan(x)
print('inverse sine: ', a)
print ('inverse cosine: ', b)
print ('inverse tangent: ',c)

inverse sine:  [-1.57079633  0.          1.57079633]
inverse cosine:  [3.14159265 1.57079633 0.        ]
inverse tangent:  [-0.78539816  0.          0.78539816]


Q3. Convert angles from radians to degrees.

In [45]:
x = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])


[-180.  -90.   90.  180.]


In [9]:
x = np.array([-np.pi, -np.pi/2, np.pi/2, np.pi])
print (np.degrees(x))

[-180.  -90.   90.  180.]


Q4. Convert angles from degrees to radians.

In [48]:
x = np.array([-180.,  -90.,   90.,  180.])


[-3.14159265 -1.57079633  1.57079633  3.14159265]


In [10]:
x = np.array([-180.,  -90.,   90.,  180.])
print (np.radians(x))

[-3.14159265 -1.57079633  1.57079633  3.14159265]


## Hyperbolic functions

Q5. Calculate hyperbolic sine, hyperbolic cosine, and hyperbolic tangent of x, element-wise.

In [65]:
x = np.array([-1., 0, 1.])


[-1.17520119  0.          1.17520119]
[ 1.54308063  1.          1.54308063]
[-0.76159416  0.          0.76159416]


In [13]:
x = np.array([-1., 0, 1.])
print (np.sinh(x))
print (np.cosh(x))
print (np.tanh(x))

[-1.17520119  0.          1.17520119]
[1.54308063 1.         1.54308063]
[-0.76159416  0.          0.76159416]


## Rounding

Q6. Predict the results of these, paying attention to the difference among the family functions.

In [14]:
x = np.array([2.1, 1.5, 2.5, 2.9, -2.1, -2.5, -2.9])

out1 = np.around(x)
out2 = np.floor(x)
out3 = np.ceil(x)
out4 = np.trunc(x)
out5 = [round(elem) for elem in x]

#print out1 = [ 2.  2.  2.  3. -2. -2. -3.]
#print out2 = [ 2.  1.  2.  2. -3. -3. -3.]
#print out3 = [ 3.  2.  3.  3. -2. -2. -2.]
#print out4 = [ 2.  1.  2.  2. -2. -2. -2.]
#print out5 = [2.0, 2.0, 2.0, 3.0, -2.0, -2.0, -3.0]

Q7. Implement out5 in the above question using numpy.

[ 2.  2.  3.  3. -2. -3. -3.]


## Sums, products, differences

Q8. Predict the results of these.

In [15]:
x = np.array(
    [[1, 2, 3, 4],
     [5, 6, 7, 8]])

outs = [np.sum(x), # = 36
        np.sum(x, axis=0), # = [6, 8, 10, 12]
        np.sum(x, axis=1, keepdims=True), # = [[10], [26]]
        "",
        np.prod(x), # = 40320
        np.prod(x, axis=0), # = [5, 12, 21, 32]
        np.prod(x, axis=1, keepdims=True), # = [[24], [1680]]
        "",
        np.cumsum(x), # = [1, 3, 6, 10, 15, 21, 28, 36]
        np.cumsum(x, axis=0), # = [[1, 2, 3, 4], [6, 8, 10, 12]]
        np.cumsum(x, axis=1), # = [[1, 3, 6, 10], [5, 11, 18, 26]]
        "",
        np.cumprod(x), # = [1, 2, 6, 24, 120, 720, 5040, 40320]
        np.cumprod(x, axis=0), # = [[1, 2, 3, 4], [5, 12, 21, 32]]
        np.cumprod(x, axis=1), # = [[1, 2, 6, 24], [5, 30, 210, 1680]]
        "",
        np.min(x), # = 1
        np.min(x, axis=0), # = [1, 2, 3, 4]
        np.min(x, axis=1, keepdims=True), # = [[1], [5]]
        "",
        np.max(x), # = 8
        np.max(x, axis=0), # = [5, 6, 7, 8]
        np.max(x, axis=1, keepdims=True), # = [[4], [8]]
        "",
        np.mean(x), # = 4.5
        np.mean(x, axis=0), # = [3, 4, 5, 6]
        np.mean(x, axis=1, keepdims=True)] # = [[2.5], [6.5]]
           
for out in outs:
    if out == "":
        pass
        print
    else:
        pass
        print("->", out)


-> 36
-> [ 6  8 10 12]
-> [[10]
 [26]]
-> 40320
-> [ 5 12 21 32]
-> [[  24]
 [1680]]
-> [ 1  3  6 10 15 21 28 36]
-> [[ 1  2  3  4]
 [ 6  8 10 12]]
-> [[ 1  3  6 10]
 [ 5 11 18 26]]
-> [    1     2     6    24   120   720  5040 40320]
-> [[ 1  2  3  4]
 [ 5 12 21 32]]
-> [[   1    2    6   24]
 [   5   30  210 1680]]
-> 1
-> [1 2 3 4]
-> [[1]
 [5]]
-> 8
-> [5 6 7 8]
-> [[4]
 [8]]
-> 4.5
-> [3. 4. 5. 6.]
-> [[2.5]
 [6.5]]


/var/folders/zd/q0vqjyzj26x22rk862mcnn0r0000gn/T/ipykernel_8765/1159245306.py:34: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if out == "":


Q9. Calculate the difference between neighboring elements, element-wise.

In [100]:
x = np.array([1, 2, 4, 7, 0])


[ 1  2  3 -7]


In [16]:
x = np.array([1, 2, 4, 7, 0])
print (np.diff(x))

[ 1  2  3 -7]


Q10. Calculate the difference between neighboring elements, element-wise, and prepend [0, 0] and append[100] to it.

In [20]:
x = np.array([1, 2, 4, 7, 0])

print (np.ediff1d(x, to_begin=[0, 0], to_end=[100]))

[  0   0   1   2   3  -7 100]


Q11. Return the cross product of x and y.

Q9. Calculate the difference between neighboring elements, element-wise.

In [21]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print (np.cross(x, y))

[-3  6 -3]


## Exponents and logarithms

Q12. Compute $e^x$, element-wise.

In [108]:
x = np.array([1, 2, 4, 7, 0])


[  0   0   1   2   3  -7 100]


In [22]:
x = np.array([1., 2., 3.], np.float32)
print (np.exp(x))

[ 2.718282   7.3890557 20.085537 ]


Q13. Calculate exp(x) - 1 for all elements in x.

In [110]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])



[-3  6 -3]


In [23]:
x = np.array([1., 2., 3.], np.float32)
print (np.exp(x)-1)

[ 1.718282   6.3890557 19.085537 ]


Q14. Calculate $2^p$ for all p in x.

Q12. Compute $e^x$, element-wise.

In [25]:
x = np.array([1., 2., 3.], np.float32)
print (np.exp2(x))

[2. 4. 8.]


Q15. Compute natural, base 10, and base 2 logarithms of x element-wise.

Q13. Calculate exp(x) - 1 for all elements in x.

In [26]:
x = np.array([1, np.e, np.e**2])
print ('natural log = ', np.log(x))
print ('common log = ', np.log10(x))
print ('base 2 log = ', np.log2(x))

natural log =  [0. 1. 2.]
common log =  [0.         0.43429448 0.86858896]
base 2 log =  [0.         1.44269504 2.88539008]


Q16. Compute the natural logarithm of one plus each element in x in floating-point accuracy.

Q14. Calculate $2^p$ for all p in x.

In [28]:
x = np.array([1e-99, 1e-100])
print (np.log1p(x))

[1.e-099 1.e-100]


## Floating point routines

Q17. Return element-wise True where signbit is set.

In [128]:
x = np.array([1, np.e, np.e**2])


natural log = [ 0.  1.  2.]
common log = [ 0.          0.43429448  0.86858896]
base 2 log = [ 0.          1.44269504  2.88539008]


In [31]:
x = np.array([-3, -2, -1, 0, 1, 2, 3])
print (np.signbit(x))
print (x<0)

[ True  True  True False False False False]
[ True  True  True False False False False]


Q18. Change the sign of x to that of y, element-wise.

In [131]:
x = np.array([1e-99, 1e-100])


[  1.00000000e-099   1.00000000e-100]


In [33]:
x = np.array([-1, 0, 1])
y = -1.1
print (np.copysign(x,y))

[-1. -0. -1.]


## Arithmetic operations

Q19. Add x and y element-wise.

In [135]:
x = np.array([-3, -2, -1, 0, 1, 2, 3])



[ True  True  True False False False False]


In [35]:
x = np.array([1, 2, 3])
y = np.array([-1, -2, -3])
print (x+y)
print (np.add(x, y))

[0 0 0]
[0 0 0]


Q20. Subtract y from x element-wise.

Q16. Compute the natural logarithm of one plus each element in x in floating-point accuracy.

In [36]:
x = np.array([3, 4, 5])
y = np.array(3)
print (x - y)
print (np.subtract(x, y))

[0 1 2]
[0 1 2]


Q21. Multiply x by y element-wise.

In [144]:
x = np.array([3, 4, 5])
y = np.array([1, 0, -1])



[ 3  0 -5]


In [37]:
x = np.array([3, 4, 5])
y = np.array([1, 0, -1])
print (x * y)
print (np.multiply(x, y))

[ 3  0 -5]
[ 3  0 -5]


Q22. Divide x by y element-wise in two different ways.

In [161]:
x = np.array([3., 4., 5.])
y = np.array([1., 2., 3.])


[ 3.          2.          1.66666667]
[ 3.  2.  1.]


In [39]:
x = np.array([3., 4., 5.])
y = np.array([1., 2., 3.])
print (x // y)
print (np.divide(x,y))

[3. 2. 1.]
[3.         2.         1.66666667]


Q23. Compute numerical negative value of x, element-wise.

In [146]:
x = np.array([1, -1])


[-1  1]


In [40]:
x = np.array([1, -1])
print (np.negative(x))

[-1  1]


Q24. Compute the reciprocal of x, element-wise.

In [155]:
x = np.array([1., 2., .2])


[ 1.   0.5  5. ]


In [41]:
x = np.array([1., 2., .2])
print (np.reciprocal(x))

[1.  0.5 5. ]


Q25. Compute $x^y$, element-wise.

In [163]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [1, 2]])


[[ 1  4]
 [ 3 16]]


In [42]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[1, 2], [1, 2]])
print (np.power(x, y))

[[ 1  4]
 [ 3 16]]


Q26. Compute the remainder of x / y element-wise in two different ways.

In [168]:
x = np.array([-3, -2, -1, 1, 2, 3])
y = 2


[1 0 1 1 0 1]
[-1  0 -1  1  0  1]


In [46]:
x = np.array([-3, -2, -1, 1, 2, 3])
y = 2
print (x % y)
print (np.mod(x, y))
print (np.fmod(x, y))

[1 0 1 1 0 1]
[1 0 1 1 0 1]
[-1  0 -1  1  0  1]


## Miscellaneous

Q27. If an element of x is smaller than 3, replace it with 3.
And if an element of x is bigger than 7, replace it with 7.

In [174]:
x = np.arange(10)


[3 3 3 3 4 5 6 7 7 7]


In [49]:
x = np.arange(10)


Q28. Compute the square of x, element-wise.

In [176]:
x = np.array([1, 2, -1])


[1 4 1]


In [50]:
x = np.array([1, 2, -1])
print (np.square(x))

[1 4 1]


Q29. Compute square root of x element-wise.


In [177]:
x = np.array([1., 4., 9.])


[ 1.  2.  3.]


In [51]:
x = np.array([1., 4., 9.])
print (np.sqrt(x))

[1. 2. 3.]


Q30. Compute the absolute value of x.

In [178]:
x = np.array([[1, -1], [3, -3]])



[[1 1]
 [3 3]]


In [52]:
x = np.array([[1, -1], [3, -3]])
print (np.abs(x))

[[1 1]
 [3 3]]


Q31. Compute an element-wise indication of the sign of x, element-wise.

In [181]:
x = np.array([1, 3, 0, -1, -3])


[ 1  1  0 -1 -1]


In [53]:
x = np.array([1, 3, 0, -1, -3])
print (np.sign(x))

[ 1  1  0 -1 -1]


In [115]:
x = np.array([1., 2., 3.], np.float32)



[  2.71828175   7.38905621  20.08553696]


In [118]:
x = np.array([1., 2., 3.], np.float32)


[  1.71828175   6.38905621  19.08553696]


In [124]:
x = np.array([1., 2., 3.], np.float32)


[ 2.  4.  8.]


In [140]:
x = np.array([-1, 0, 1])
y = -1.1


[-1. -0. -1.]


In [141]:
x = np.array([1, 2, 3])
y = np.array([-1, -2, -3])



[0 0 0]


In [142]:
x = np.array([3, 4, 5])
y = np.array(3)



[0 1 2]
