# Linear algebra

In [3]:
import numpy as np

## Matrix and vector products

Q1. Predict the results of the following code.

In [53]:
x = [1,2]
y = [[4, 1], [2, 2]]
#print np.dot(x, y) = [8, 5] = [4*1+2*2, 1*1+2*2] # tich so cham
#print np.dot(y, x) = [6, 6] = [4*1+2*1, 1*2+2*2] # tich so cham
#print np.matmul(x, y) = [8, 5] #tich ma tran
#print np.inner(x, y) = [6, 6] # tich ben trong
#print np.inner(y, x) = [6, 6]

Q2. Predict the results of the following code.

In [1]:
x = [[1, 0], [0, 1]]
y = [[4, 1], [2, 2], [1, 1]]
#print np.dot(y, x) = [[4, 1], [2, 2], [1, 1]] = [[1*4+0*1, 0*4+1*1], [1*2+0*2, 0*2+1*2], [1*1+0*1, 0*1+1*1]]
#print np.matmul(y, x) = [[4, 1], [2, 2], [1, 1]]

Q3. Predict the results of the following code.

In [37]:
x = np.array([[1, 4], [5, 6]])
y = np.array([[4, 1], [2, 2]])
#print np.vdot(x, y) = 30
#print np.vdot(y, x) = 30
#print np.dot(x.flatten(), y.flatten()) = 30
#print np.inner(x.flatten(), y.flatten()) = 30
#print (x*y).sum() = 30

Q4. Predict the results of the following code.

In [4]:
x = np.array(['a', 'b'], dtype=object)
y = np.array([1, 2])
#print np.inner(x, y) = abb
#print np.inner(y, x) = abb
#print np.outer(x, y) = [['a' 'aa'],['b' 'bb']]
#print np.outer(y, x) = [['a' 'b'],['aa' 'bb']]

## Decompositions

Q5. Get the lower-trianglular `L` in the Cholesky decomposition of x and verify it.

In [97]:
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=np.int32)


[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]


In [7]:
x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], dtype=np.int32)
print(np.linalg.cholesky(x))

[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]


Q6. Compute the qr factorization of x and verify it.

In [107]:
x = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=np.float32)


q=
[[-0.85714287  0.39428571  0.33142856]
 [-0.42857143 -0.90285712 -0.03428571]
 [ 0.2857143  -0.17142858  0.94285715]] 
r=
[[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]


In [10]:
x = np.array([[12, -51, 4], [6, 167, -68], [-4, 24, -41]], dtype=np.float32)
q, r = np.linalg.qr(x)
print (q,r)

[[-0.85714287  0.3942857   0.33142856]
 [-0.42857143 -0.9028571  -0.03428571]
 [ 0.2857143  -0.17142858  0.94285715]] [[ -14.  -21.   14.]
 [   0. -175.   70.]
 [   0.    0.  -35.]]


Q7. Factor x by Singular Value Decomposition and verify it.

In [165]:
x = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)


U=
[[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]] 
s=
[ 3.          2.23606801  2.          0.        ] 
V=
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [15]:
x = np.array([[1, 0, 0, 0, 2], [0, 0, 3, 0, 0], [0, 0, 0, 0, 0], [0, 2, 0, 0, 0]], dtype=np.float32)
u, s, v = np.linalg.svd(x)
print (u, s, v)

[[ 0.  1.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 0.  0.  1.  0.]] [3.       2.236068 2.       0.      ] [[-0.         0.         1.         0.         0.       ]
 [ 0.4472136  0.         0.         0.         0.8944272]
 [-0.         1.         0.         0.         0.       ]
 [ 0.         0.         0.         1.         0.       ]
 [-0.8944272  0.         0.         0.         0.4472136]]


## Matrix eigenvalues

Q8. Compute the eigenvalues and right eigenvectors of x. (Name them eigenvals and eigenvecs, respectively)

In [77]:
x = np.diag((1, 2, 3))


eigenvalues are
[ 1.  2.  3.]
eigenvectors are
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [19]:
x = np.diag((1, 2, 3))
w, v = np.linalg.eig(x)
print (w, v)

[1. 2. 3.] [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Q9. Predict the results of the following code.

In [23]:
#print np.array_equal(np.dot(x, eigenvecs), eigenvals * eigenvecs)

## Norms and other numbers

Q10. Calculate the Frobenius norm and the condition number of x.

In [12]:
x = np.arange(1, 10).reshape((3, 3))


16.8819430161
4.56177073661e+17


In [31]:
x = np.arange(1, 10).reshape((3, 3))
print (np.linalg.norm(x, 'fro'))
print (np.linalg.cond(x, 'fro')) # sao khong giong dap an nhi, search numpy.org ra dung ham nay ma?

16.881943016134134
3.193239515623568e+17


Q11. Calculate the determinant of x.

In [22]:
x = np.arange(1, 5).reshape((2, 2))


-2.0


In [32]:
x = np.arange(1, 5).reshape((2, 2))
print (np.linalg.det(x))

-2.0000000000000004


Q12. Calculate the rank of x.

In [35]:
x = np.eye(4)


4


In [33]:
x = np.eye(4)
print (np.linalg.matrix_rank(x))

4


Q13. Compute the sign and natural logarithm of the determinant of x.

In [49]:
x = np.arange(1, 5).reshape((2, 2))



-1.0 0.69314718056


In [34]:
x = np.arange(1, 5).reshape((2, 2))
print (np.linalg.slogdet(x))

(-1.0, 0.6931471805599455)


Q14. Return the sum along the diagonal of x.

In [57]:
x = np.eye(4)


4.0


In [35]:
x = np.eye(4)
print (np.trace(x))

4.0


## Solving equations and inverting matrices

Q15. Compute the inverse of x.

In [60]:
x = np.array([[1., 2.], [3., 4.]])



[[-2.   1. ]
 [ 1.5 -0.5]]


In [36]:
x = np.array([[1., 2.], [3., 4.]])
y = np.linalg.inv(x)
print (y)

[[-2.   1. ]
 [ 1.5 -0.5]]
