# Array creation routines

## Ones and zeros

In [1]:
import numpy as np

Create a new array of 2*2 integers, without initializing entries.

In [17]:
# Tao mang trong 2*2
np.empty([2,2], int)

array([[0, 0],
       [0, 0]])

Let X = np.array([1,2,3], [4,5,6], np.int32). 
Create a new array with the same shape and type as X.

In [5]:
# Tao mang co cung shape & type voi X
X = np.array(([1,2,3], [4,5,6]), np.int32)
arr2 = np.empty_like(X)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

Create a 3-D array with ones on the diagonal and zeros elsewhere.

In [18]:
# Tao mang 3 chieu voi cac phan tu la so 0 & so 1 tao thanh duong cheo
arr3 = np.eye(3,3)
arr3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
arr3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Create a new array of 3*2 float numbers, filled with ones.

In [11]:
# Tao mang 3*2 voi cac phan tu la so thuc co gia tri 1
arr4 = np.ones((3,2), dtype = float)
arr4

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

Let x = np.arange(4, dtype=np.int64). Create an array of ones with the same shape and type as X.

In [26]:
# Tao mang co cung shape & type voi X co cac phan tu co gia tri 1
x = np.arange(4, dtype=np.int64)
arr5 = np.full_like(x, 1)
arr5

array([1, 1, 1, 1], dtype=int64)

Create a new array of 3*2 float numbers, filled with zeros.

In [22]:
# Tao mang 3*2 voi cac phan tu la so thuc co gia tri 1
arr6 = np.zeros((3,2), float)
arr6

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Let x = np.arange(4, dtype=np.int64). Create an array of zeros with the same shape and type as X.

In [27]:
# Tao mang co cung shape & type voi X co cac phan tu co gia tri 0
x = np.arange(4, dtype=np.int64)
arr7 = np.full_like(x, 0)
arr7

array([0, 0, 0, 0], dtype=int64)

Create a new array of 2*5 uints, filled with 6.

In [30]:
# Tao mang 2*5 co cac phan tu co gia tri 6
arr8  = np.full((2,5), fill_value = 6, dtype = np.uint32)
arr8

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint32)

Let x = np.arange(4, dtype=np.int64). Create an array of 6's with the same shape and type as X.

In [31]:
# Tao mang co cung shape & type voi X co cac phan tu co gia tri 6
x = np.arange(4, dtype=np.int64)
arr9 = np.full_like(x, 6)
arr9

array([6, 6, 6, 6], dtype=int64)

## From existing data

Create an array of [1, 2, 3].

In [34]:
#Tao mang voi [1, 2, 3]
arr10 = np.array([1, 2, 3])
arr10

array([1, 2, 3])

Let x = [1, 2]. Convert it into an array.

In [35]:
# Chuyen doi x thanh mang
x = [1, 2]
arr11 = np.array(x)
arr11

array([1, 2])

Let X = np.array([[1, 2], [3, 4]]). Convert it into a matrix.

In [38]:
# Chuyen X thanh matrix
X = np.array([[1, 2], [3, 4]])
m1 = np.matrix(X)
m1

matrix([[1, 2],
        [3, 4]])

Let x = [1, 2]. Conver it into an array of `float`.

In [37]:
# Chuyen x thanh mang co kieu float
x = [1, 2]
arr12 = np.array(x, float)
arr12

array([1., 2.])

Let x = np.array([30]). Convert it into scalar of its single element, i.e. 30.

In [39]:
# Chuyen doi x thanh 1 phan tu don le
x = np.array([30])
x.item()

30

Let x = np.array([1, 2, 3]). Create a array copy of x, which has a different id from x.

In [42]:
# Tao 1 mang copy tu x
x = np.array([1, 2, 3])
y = np.copy(x)
print(id(y), y)
print(id(x), x)

2552747593040 [1 2 3]
2552748207920 [1 2 3]


## Numerical ranges

Create an array of 2, 4, 6, 8, ..., 100.

In [44]:
# Tao mang 1D 1 day so tu 2 den 100 cach nhau 2 don vi
arr13 = np.arange(2, 102, 2)
arr13

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

Create a 1-D array of 50 evenly spaced elements between 3. and 10., inclusive.

In [45]:
# Tao mang 1D co 50 phan tu o giua 3 va 10 (bao gom 10)
arr14 = np.linspace(3, 10, num = 50, endpoint = True)
arr14

array([ 3.        ,  3.14285714,  3.28571429,  3.42857143,  3.57142857,
        3.71428571,  3.85714286,  4.        ,  4.14285714,  4.28571429,
        4.42857143,  4.57142857,  4.71428571,  4.85714286,  5.        ,
        5.14285714,  5.28571429,  5.42857143,  5.57142857,  5.71428571,
        5.85714286,  6.        ,  6.14285714,  6.28571429,  6.42857143,
        6.57142857,  6.71428571,  6.85714286,  7.        ,  7.14285714,
        7.28571429,  7.42857143,  7.57142857,  7.71428571,  7.85714286,
        8.        ,  8.14285714,  8.28571429,  8.42857143,  8.57142857,
        8.71428571,  8.85714286,  9.        ,  9.14285714,  9.28571429,
        9.42857143,  9.57142857,  9.71428571,  9.85714286, 10.        ])

Create a 1-D array of 50 element spaced evenly on a log scale between 3. and 10., exclusive.

In [47]:
# Tao mang 1D co 50 phan tu o giua 3 va 10 (khong bao gom 10)
arr15 = np.logspace(3, 10, num = 50, endpoint = False)
arr15

array([1.00000000e+03, 1.38038426e+03, 1.90546072e+03, 2.63026799e+03,
       3.63078055e+03, 5.01187234e+03, 6.91830971e+03, 9.54992586e+03,
       1.31825674e+04, 1.81970086e+04, 2.51188643e+04, 3.46736850e+04,
       4.78630092e+04, 6.60693448e+04, 9.12010839e+04, 1.25892541e+05,
       1.73780083e+05, 2.39883292e+05, 3.31131121e+05, 4.57088190e+05,
       6.30957344e+05, 8.70963590e+05, 1.20226443e+06, 1.65958691e+06,
       2.29086765e+06, 3.16227766e+06, 4.36515832e+06, 6.02559586e+06,
       8.31763771e+06, 1.14815362e+07, 1.58489319e+07, 2.18776162e+07,
       3.01995172e+07, 4.16869383e+07, 5.75439937e+07, 7.94328235e+07,
       1.09647820e+08, 1.51356125e+08, 2.08929613e+08, 2.88403150e+08,
       3.98107171e+08, 5.49540874e+08, 7.58577575e+08, 1.04712855e+09,
       1.44543977e+09, 1.99526231e+09, 2.75422870e+09, 3.80189396e+09,
       5.24807460e+09, 7.24435960e+09])

## Building matrices

Let X = np.array([[ 0,  1,  2,  3],
                  [ 4,  5,  6,  7],
                 [ 8,  9, 10, 11]]).
                 Get the diagonal of X, that is, [0, 5, 10].

In [59]:
# Chon cac phan tu tu mang X
X = np.array([[ 0, 1, 2, 3], [ 4, 5, 6, 7], [ 8, 9, 10, 11]])
Y = np.diagonal(X)
Y

array([ 0,  5, 10])

Create a 2-D array whose diagonal equals [1, 2, 3, 4] and 0's elsewhere.

In [60]:
# Tao mang co duong cheo la 1 2 3 4 va cac phan tu con lai la 0
a = [1, 2, 3, 4]
arr16 = np.diagflat(a)
arr16

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

Create an array which looks like below.
array([[ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.,  0.]])

In [6]:
# Tao mang 3*5 voi so 1 nam duoi duong cheo, cac phan tu con lai bang 0
arr17 = np.tri(3, 5, -1)
arr17

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

Create an array which looks like below.
array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

In [7]:
# Tao mang 4*3 voi cac so nam duoi duong cheo, cac phan tu con lai bang 0
arr18 = np.tril(np.arange(1, 13).reshape(4, 3), -1)
arr18

array([[ 0,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  0],
       [10, 11, 12]])

Create an array which looks like below. array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

In [10]:
# Tao mang 4*3 voi cac so nam duoi duong cheo, cac phan tu con lai bang 0
arr19 = np.triu(np.arange(1, 13).reshape(4, 3), -1)
arr19

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])